name 'netmanagers-nut'
version '1.0.7'

author 'Sebastian Quaino'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source 'https://github.com/netmanagers/puppet-nut'
summary 'Puppet module for nut'
description 'This module installs and manages nut. Check README for details.'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
